### ISSUE TITLE
properties view: make entities clickable 

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/apis-core-rdf#1]
# Properties View: Entities should be links

## Current Behaviour

In the list of properties (e.g. [TibSchol](https://tibschol.acdh-dev.oeaw.ac.at/apis/relations/property/list/)) both Subject and Object are just provided as strings. 

![grafik](https://user-images.githubusercontent.com/4641281/190584025-399c02b6-8e5f-4691-a7d4-ec40416dc86d.png)

## Expected Behaviour

Subject and Object should be clickable links and point to the detail view of the instance.

**Comment by dasch124** [comment]
I hope this is the right place to report this

**Comment by steffres** [comment]
Yes, this is the right place. I'm aware of this issue and will work on it soon.

**Comment by koeaw** [comment]
Quick question because I'm working on something related #23 – the problematic view reported here is that for Triples, right?

The assumption being that even though Triples & Properties pages currently show the exact same thing, Properties is really supposed to list which entity combinations are possible (i.e. subject-predicate-object combos where subject and object are entity class names, not entity _objects_).

**Comment by steffres** [comment]
Note that this issue is still open with the recent introduction of forms and tables too.

**Comment by b1rger** [comment]
Sorry for the delay, the linked entities in the properties view will be part of apis-core-rdf v0.13.1
