### ISSUE TITLE
Column sorting seems broken

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#1022]
I just tried sorting my table columns on `v0.23.0` by clicking on the column headers, which made all columns except for the icon columns disappear and emptied the "additional columns" dropdown.

Tried this with several tables and the behaviour seems to slightly differ between them, e.g. for ones with custom columns all columns except those custom ones (and the icon columns) disappear.

I.e. seems like columns for "proper" fields are affected? Will investigate further.

**Comment by b1rger** [comment]
Ah, yeah. This is due to this assignment:
https://github.com/acdh-oeaw/apis-core-rdf/blob/d0bffdb7b31ded5ab0bbfa5a498f28ec0dc9ba48/apis_core/generic/views.py#L111

if there is a get parameter, but it does not contain the `columns`, that is interpreted as an emtpy list of columns. I guess we should find out how to append the sorting of the table to the existing parameters

**Comment by koeaw** [comment]
Hmm, so this seems to happen when I try to sort on the default view of a table.

When I first actively add or remove a column via the "addional columns" dropdown, and only _then_ sort, all columns in the table remain in place.
