### ISSUE TITLE
CreateRelationsForm - django fields with choices are displayed as autocomplete (without any options)

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1193]
When a relationship class has a choices field then the following code in ```apis-core-rdf/apis_core/relations/views.py```
converts it into an AutoComplete field but the choices are lost.
```
    def get(self, *args, **kwargs):
        resp = super().get(*args, **kwargs)
        content_type = ContentType.objects.get_for_model(self.model)
        resp["HX-Trigger-After-Settle"] = (
            '{"reinit_select2": "relation_' + content_type.model + '_form"}'
        )
        return resp
```
~I couldn't see any loss in the autocomplete functionality when I removed this method; and~ once I remove this function my choices field also works fine as a dropdown.
 
@b1rger is my understanding correct?

**Comment by b1rger** [comment]
This trigger is needed because it reinitializes the select2 autocompletes in the modals. This is done in https://github.com/acdh-oeaw/apis-core-rdf/blob/49c21bc37e38b5ba99e9749b9e6a3ba24da28010/apis_core/relations/templates/apis_core/apis_entities/abstractentity_form.html#L14
Maybe this javascript function should be more specific which select inputs it is working on

**Comment by b1rger** [comment]
If you open a relation form and then close it without sending it and then reopening it, then the autocomplete is somehow broken. The javascript eventlistener fixes that.
