### ISSUE TITLE
bug(apis_entities): unable to create a record via autocomplete Create option 

### ISSUE THREAD

**Issue by gythaogg** [acdh-oeaw/apis-core-rdf#1363]
In the Edit view or Create view I am not able to create a new value for a M2M field - when I click on **Create** in the autocomplete dropdown list I get this error: `'NoneType' object has no attribute 'pk'`

![image](https://github.com/user-attachments/assets/9a178234-2ae9-4785-9412-a146efd4d5b8)

**Comment by b1rger** [comment]
Is this something you want to be able to do? So far the autocomplete `Create...` option in APIS was only used for creating objects from URIs. We can adapt that to make it possible to create objects from arbitrary strings, the project just has to configure what to do with those strings (should it be a forename? a surname? a label?...)
The autocomplete view by default uses the value from the form field to create a new object and then set the value to be the primary key - because we returned `None` if the creation does not work (see #1398) it returns the error message you see

**Comment by b1rger** [comment]
> The autocomplete view by default uses the value from the form field to create a new object and then set the value to be the primary key

That was wrong, what actually happens is that the autocomplete view creates the object and uses the value to set a preconfigured attribute of the new instance

> Is there a way for the user to tell which fields can create objects from URIs - or turn off this Create option altogether if the project or field doesn't have a create from URI option?

In #1396 I changed the autocomplete to only show the `Create ...` option if the form actively requests that - and the PR does that only in the `relations` forms.

**Comment by b1rger** [comment]
This behaviour was disabled in 6995a73d6722f379f0d2cb0f22658fb47901e1b8, so I'm closing this issue
