### ISSUE TITLE
Discuss `uri_resolver`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#167]
The `/uri_resolver` endpoint is broken (after some fixing in `api_views.uri_resolver` it still throws an exception: it uses the `TeiEntCreator` but this fails, because the `entity_type_string_to_class` mapping is commented). Is this endpoint still being used? This also relates to #166

**Comment by sennierer** [comment]
decided in Jfx:
- should provide an APAI endpoint that gets as a parameter an URI and returns the data format set via accept headers for the objects
- should use the `get` function of the URI model and redirect to the correct API endpoint
- check if there is already an endpoint that provide this functionality

**Comment by sennierer** [comment]
there is an existing route for this functionality: `apis/api2/uri?uri=URI&target_format=FORMAT`
should be moved to /apis, included in the swagger and refactored to use `format` as query parameter instead of `target_format`
Currently this is broken in apis-rdf due to other foreign key in the URI model.

**Comment by b1rger** [comment]
I just realized that there is also the `/apis/api/metainfo/uri/` endpoint, which lists Uris and also lets search (or filter) for Uris. I guess the endpoint we are talking about should then be called `uritoobject` or something similar.
