### ISSUE TITLE
Need to save current user name in model field

### ISSUE THREAD

**Issue by richardhadden** [acdh-oeaw/apis-core-rdf#226]
We want to be able to save the logged-in user name to a model field on creation.

Can modify the `<model>.save` method, or add signal, but no access to the request lifecycle from these methods.

Options:
- Change the POST request handler/form to add this data somehow, or pass on extra data to `<model>.save` — this functionality would probably produce a breaking change?
- Some kind of middleware, which apparently @b1rger knows?

**Comment by b1rger** [comment]
> Some kind of middleware, which apparently @b1rger knows?

https://stackoverflow.com/questions/4716330/accessing-the-users-request-in-a-post-save-signal

**Comment by b1rger** [comment]
The official Django docs suggest to set the field in form validation: https://docs.djangoproject.com/en/4.2/topics/class-based-views/generic-editing/#models-and-request-user

**Comment by richardhadden** [comment]
The latter does sound more sensible (less of a hack, at least). I guess there's no easy way to override the whole form though? The middleware approach does work, incidentally

**Comment by b1rger** [comment]
> The latter does sound more sensible (less of a hack, at least). I guess there's no easy way to override the whole form though? The middleware approach does work, incidentally

Yes, you're right, there is currently no way to override the form, so for now the middleware is the way to go. I've created #238 to track that, I think it would be a good feature and we also allow to override other parts

**Comment by koeaw** [comment]
Unrelated: the [triage](https://github.com/acdh-oeaw/apis-core-rdf/labels/triage) label exists to signal a ticket may not have been properly labelled yet (useful e.g. when non-contributors open new issues). It's meant to be removed/replaced (or never be created in the first place when we ourselves create tickets).

**Comment by b1rger** [comment]
It turns out that APIS already depends on `django-crum` (CRUM for [Current Request User Middleware](https://django-crum.readthedocs.io/en/latest/)) which provides exactly that functionality. It is being used in https://github.com/acdh-oeaw/apis-core-rdf/blob/872386eb35640f1bf13b8716e5ac696422ffc970/apis_core/apis_relations/models.py#L6

Not sure if that funcionality is being used, but the `django-crum` package could be a solution to the original request. Or did you solve the problem another way, @richardhadden ?

**Comment by b1rger** [comment]
No response in 3 month, therefore closing
