### ISSUE TITLE
allow to hook additional suggestions to entities autocompletes

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#247]
in relation to #240 and #245 
In vanilla APIS we had the possibility to search through external reference resources and directly import (via the RDF Parser) metadata of selected entities in the db. That functionality was actually working very well and increased the productivity in the tool.

To get that functionality also in the apis-rdf version we need to:
- rewrite the autocomplete class to pull in additional suggestions from eg `self.get_additional_suggestions()` if the definition exists
- and a setting that allows to set the autocomplete class used for creating the suggestions for the given entity

This will allow the user of the tool to inherit from the generic base autocomplete class and overwrite only `self.get_additional_suggestions()` or completely replace the class with a custom logic.

**Comment by richardhadden** [comment]
I was just looking at the possibility of using Postgres full text search (uses the `MODEL.objects.filter(FIELD__search="something")`) method, which would involve adding some additional logic around here (https://github.com/acdh-oeaw/apis-core-rdf/blob/7dfa2ac1d8ad97584a55f9b5c865e451959971a0/apis_core/apis_entities/autocomplete3.py#L139) to check whether the field should use a full-text search rather than `__icontains` or whatever. But this is probably something that will need to be set in `settings.APIS_ENTITIES`?

**Comment by b1rger** [comment]
Done in cbad572207d419e5a8ed5be1d8bb8315054cd407
