### ISSUE TITLE
Remove TempTriple in Favor of simple Triples and Reifications

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#4]
TempTriples were implemented for the sake of downwards-compatibility to Vanilla. 

But we have agreed to remove them to be more RDF compliant and also because the TempTriples would again be some kind of semantic hard-wiring into the code (A few edge cases where they are needed do not justify that they are implemented everywhere).

TempTriples will be removed in favor of either arbitrarily sub-classed triples or reificated properties. The relevant issue for this is: https://github.com/acdh-oeaw/apis-core-rdf/issues/3

**Comment by steffres** [comment]
With the introduction of Reifications we can now drop TempTriples. 

### What are reifications?

Classes that act as complex relations, having attributes themselves and able to relate arbitrary amount of entity classes and instances too, also they are not able to exist on their own, but always depend on other entities.

It's a common pattern in RDF and we replicate this. In your ontology you can define your own reification identical to entities with the difference that it needs to inherit from `AbstractReification`.

### How do we replace TempTriples with Reifications?

The general procedure would look like this:

* All TempTriples that **only use subj, obj, prop** are replaced with simple triples. No need from your side to do anything here.

* All TempTriples **that also use some of their additional attribute fields** (e.g.`start_date_written` ) need to be replaced with dedicated Reification classes.

Assume your users have utilized the `start_date_written` field of TempTriple only between the entities `Person` and `Place` and the property would be `visited`. The semantics of the date would be that the relation expresses the visit has happened at a certain date.

Now to replace this we could introduce a Reification class named `VisitRelation` with an DateField `date of visit`, and further we need now two instead of one properties: one from `Person` to  `VisitRelation` (e.g. `did visit`) and one from `VisitRelation` to `Place` (e.g. `took place in`). 

Yes, this is semantically more cumbersome, but it's RDF. 

I mititaged the clumsiness a bit by pre-selecting the property if there is only one anyway, so in most cases the users would not need to type in `did` or `took place in`.

In code this could look like this:
```
@reversion.register(follow=["tempentityclass_ptr"])
class Person(TempEntityClass):
    pass

@reversion.register(follow=["tempentityclass_ptr"])
class Place(TempEntityClass):
    pass

class VisitRelation(AbstractReification):
    date_of_visit = models.DateField(blank=True, null=True)
    
did_visit = Property.objects.create(name="did visit")
did_visit.subj_class.add(ContentType.objects.get(model=Person.__name__))
did_visit.obj_class.add(ContentType.objects.get(model=VisitRelation.__name__))

took_place_in = Property.objects.create(name="took place in")
took_place_in.subj_class.add(ContentType.objects.get(model=VisitRelation.__name__))
took_place_in.obj_class.add(ContentType.objects.get(model=Place.__name__))
```

The UI does only display classes that inherit from `AbstractEntity` as primary editable things. Classes that inherit from `AbstractReification` are handled separately in dedicated form logic on the right pane below the usual relations. Basically from UX side they behave like fancy relations.

Besides attaching attributes onto complex relations, this allows us to define very complex relations too with multiple related entities, something that did occasionally pop up in the past in other projects.

### script to help with migration

I wrote a management script that checks for existing data in TempTriples and fetches the related classes to get an overview of what the new Reifications need to cover. 

The script is here https://github.com/acdh-oeaw/apis-rdf-devops/blob/dev/webpage/management/commands/check_and_migrate_tec_tt.py and can be executed like so:

```
./manage.py check_and_migrate_tec_tt tec # tec for TempEntityClass
./manage.py check_and_migrate_tec_tt tt # tt for TempTriple
```
Currently it will **not execute any migration**, only checking for replacement attributes / classes, so feel free to run it and check the output. 

And the output could look like this for example where there is 13 TempTriples between `F10_Person` -`p2 has type`-> `E55_Type` which need to have a replacement reification.

```
New Reification class needed:
between class (as 'subject'): F10_Person
and class (as 'object'): E55_Type
replacing current property: p2 has type

Currently there are TempTriple with these subjects, objects, property with these fields and number of occurrences:
references = models.TextField(blank=True, null=True) # number of occurrences: 13

The new Reification pattern should look like this:
F10_Person -'prop_entity_to_reification'-> 'NewReificationClass' -'prop_reification_to_entity'-> E55_Type

where you need to create:
'prop_entity_to_reification'
'prop_reification_to_entity'
'NewReificationClass'
Take the fields from above and add them to 'NewReificationClass'
```

**Comment by sennierer** [comment]
as said in one of the last Jfx we should keep the adaptions that need migration in a dedicated branch for the moment and allow the different projects through poetry groups to install it or stay with the old version for the moment. this allows us to migrate every project as soon as its ready.

**Comment by sennierer** [comment]
not used anymore, closing
