### ISSUE TITLE
Fix `delete` button in edit view

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#437]
The `delete` button in the edit view leads to 404, it should point to the delete view of the entity

**Comment by koeaw** [comment]
I found an existing template [confirm_delete.html](https://github.com/acdh-oeaw/apis-core-rdf/blob/main/apis_core/core/templates/confirm_delete.html ) for displaying to-be-deleted items in `apis_core/core/templates` – do I need to (re)use that one? Or can I recreate it just for entities in  `apis_core/apis_entities/templates/apis_entities/`? If only for now?

The template needs cleaning up but this issue is already more time-consuming than I thought it would be, so I want to avoid adding more complexity by having to make sure I don't break anything for the [other](https://github.com/acdh-oeaw/apis-core-rdf/blob/5b2bfd6de18e074edcc52282943e054d06e19f39/apis_core/apis_labels/views.py#L56) [views](https://github.com/acdh-oeaw/apis-core-rdf/blob/5b2bfd6de18e074edcc52282943e054d06e19f39/apis_core/apis_metainfo/views.py#L50) that make use of it.

**Comment by b1rger** [comment]
You don't have to touch the `confirm_delete.html` template. This issue is about this line in the `edit_generic.html` template: https://github.com/acdh-oeaw/apis-core-rdf/blob/5b2bfd6de18e074edcc52282943e054d06e19f39/apis_core/apis_entities/templates/apis_entities/edit_generic.html#L106

which has `delete` hardcoded as href and therefore leads to a 404. It should point to the delete view of the entity that is edited, so either `/apis/entities/entity/{entity_class}/{object.id}/delete` or even better, to the `generic_entities_delete_view` url pattern name defined in:

https://github.com/acdh-oeaw/apis-core-rdf/blob/5b2bfd6de18e074edcc52282943e054d06e19f39/apis_core/apis_entities/urls.py#L36

**Comment by koeaw** [comment]
Aha. So I looked at something different based on a misunderstanding on what the issue was about, but ran into a different problem in the process, which is what I've been working on.

I never looked at the edit _template_, only the edit _view_, and started from the only place I knew had a delete button, which is the detail view. Deleting is broken for me _there_, so it didn't occur to me to that this was about something else that's much simpler. o__O

Well, ok... I'll look into this smaller thing as well, but with the amount of time I've spent on this now, I'll mostly submit what I've come up with to fix the (larger) problem on my end. (Which may need further adaptation for other projects.)

**Comment by koeaw** [comment]
Well I guess I'll open a separate issue & create a separate PR for my underlying problem with deleting.

**Comment by koeaw** [comment]
Draft PR for the more general fix is here: https://github.com/acdh-oeaw/apis-core-rdf/pull/458

**Comment by b1rger** [comment]
> Draft PR for the more general fix is here: #458

Just FTR, #458 does not solve **this** issue

**Comment by koeaw** [comment]
Well, the actual fix for this issue was indeed easy! :upside_down_face::stuck_out_tongue_closed_eyes:
