### ISSUE TITLE
Integration of GenericForeignKeys/GenericRelations into views

### ISSUE THREAD

**Issue by koeaw** [acdh-oeaw/apis-core-rdf#456]
Our reworked entity classes contain `GenericRelation`s to other classes – how do I make those show up in our views? Do I need to overwrite the existing default views for our app or should (can) the defaults in core be adapted to work with `GenericForeignKey`/`GenericRelation`?

For now, I simply added them to our `APIS_ENTITIES` settings like any regular field, which results in an error in the list view (and gets ignored in e.g. the detail view).

I know that previously, foreign keys used with `TempEntityClass` would show up in _some_ views, but I don't know if that was only because they were written into those views or _also_ because they were "proper" foreign keys.

**Comment by b1rger** [comment]
* for the detailview: override/extend the template and add the generic relation
* for the listview: since v0.7.0 is is possible to override the table that is used for the listview, by adding a table class to `yourapp.tables.<Entityname>Table`, so if your app is called `apis_ontology` and your entity is called `Person` then the class `apis_ontology.tables.PersonTable` is used to override the default table

Please create an issue for the error you encountered
