### ISSUE TITLE
Make fields in display view configurable

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#47]
At the moment die fields displayed in the `General Info` card on the left side
of an entity detail view are hardcoded. These fields should be configurable,
ideally via the `APIS_ENTITIES` dict.

**Comment by koeaw** [comment]
Very cool, this is something that's been missing for us/our team, too.

Lack of configurability aside, one of our entities displays differently from all the rest but I don't know why (haven't yet had time to look into it). It's one of the default ones in vanilla, so I thought it may be related to that, however, another default one we also (re)use does does not exhibit this behaviour, so idk.

Either way, I thought I'd mention it just in case.

**Comment by koeaw** [comment]
GitLab issue, for reference: https://gitlab.oeaw.ac.at/acdh-ch/frischmuth/backend/apis-core-rdf/-/issues/3

**Comment by b1rger** [comment]
Given that the detailview is being rewritten (https://github.com/acdh-oeaw/apis-core-rdf/blob/sresch__reification_dynamic_triple_vocab_form/apis_core/apis_entities/detail_generic.py) it might make sense to wait with this

**Comment by steffres** [comment]
well spotted Birger, however that part will not be touched, so work on this can continue.

**Comment by b1rger** [comment]
> well spotted Birger, however that part will not be touched, so work on this can continue.

My initial approach would have been to move the `get_relevant_fields` method to the respective classes, that way it would be configurable per model.
But I now realized that the view passes the whole instance to the template, which is good, because that means that we can simply override the template and ship one that lists the fields we are interested in. Isn't this a cleaner approach than adding a configuration setting?

**Comment by steffres** [comment]
Yes, there are multiple approaches:

* define the fields in a settings dict (be it now attached to the model class or in the global settings module)
* define methods within the respective classes
* override template with custom ones defined for the individual classes (if exists of course, otherwise some fallback option)

I agree that the option of passing ad hoc templates is clean and modular and should be looked into. 

However given the fact that currently our entity settings are inconsistent (attached to model vs global settings module) and tidying this inconsistency up is quite a small effort, we should prioritize this first. 

Since throughout our codebase we utilize the settings dict approach often, let's stick to this for now and focus on higher priority issues. 

Once this is made consistent it would also be easier to refactor in favor of some other approach too.

**Comment by b1rger** [comment]
I'm closing this, because it is possible now to override what is displayed for an entity on various levels: the `detail_generic.html` template contains an `info-table` block, which, by default, displays all the fields. There is a hardcoded list of fields that are excluded in: https://github.com/acdh-oeaw/apis-core-rdf/blob/819dabb74beb27eb8c7d00bbcebcf6f2a20f852e/apis_core/apis_entities/detail_generic.py#L116 but that will be dropped once `TempEntity` is gone.
Additionaly, it is possible to exclude fields via the `APIS_ENTITIES['entityname']['detail_view_exclude']` list.

Simply overriding the template is probably the easiest approach
