### ISSUE TITLE
Property subject / object classes are not updated when entity classes change

### ISSUE THREAD

**Issue by SteffRhes** [acdh-oeaw/apis-core-rdf#55]
In the UI when the user would query for a property in a related triple from, only properties are loaded which are assigned directly to the given entity classes at hand. No subclassing of entites and hence their valid properties is respected.

Richard stumpled upon this with the following example that I could recreate:

```
class Place(TempEntityClass):
    ...

class Person(TempEntityClass):
    ...

class Musician(Person):
    ...


person_has_place_of_birth = Property.objects.get_or_create(
        name="has place of birth",
        name_reverse="is place of birth of",
    )[0]
person_has_place_of_birth.subj_class.add(ContentType.objects.get(model=Person.__name__))
person_has_place_of_birth.obj_class.add(ContentType.objects.get(model=Place.__name__))
```

In the UI when relating a musician to a place, the property `has place of birth` is not loaded.

However on the underlying data architecture, the allowed subclasses are correctly loaded of a given property.

E.g. following the example above in the shell:
```
In [4]: person_has_place_of_birth.subj_class.all()
Out[4]: <QuerySet [<ContentType: apis_ontology | person>, <ContentType: apis_ontology | musician>]>
```

**Comment by steffres** [comment]
However, in my recent refactoring of the triple forms I tried this on my instance and the property autocomplete did respect the subclassing. 

So, let's look into this again, once my recent refactoring is rolled out. Might just be fixed by it by accident.

**Comment by steffres** [comment]
A likely cause is when some of the entity classes change that do not update the corresponding properties.

E.g. assume these models and this property:
```
class Place(TempEntityClass):
    pass

class Person(TempEntityClass):
    pass

person_has_place_of_birth = Property.objects.get_or_create(
    name="has place of birth",
    name_reverse="is place of birth of",
)[0]
person_has_place_of_birth.subj_class.add(ContentType.objects.get(model=Person.__name__))
person_has_place_of_birth.obj_class.add(ContentType.objects.get(model=Place.__name__))
```

Further assume an entity is defined after the above was executed and migrated. E.g.:
```
class Musician(Person):
    pass
```
Then the property does not pick up the new child class:
```
In [6]: person_has_place_of_birth.subj_class.all()
Out[6]: <QuerySet [<ContentType: apis_ontology | person>]>
```

The current logic for checking for class inheritance in relation that can be used as subjects or objects in a property is here:
https://github.com/acdh-oeaw/apis-core-rdf/blob/dev/apis_core/apis_relations/models.py#L123

And is initiated on a django orm change signal here:
https://github.com/acdh-oeaw/apis-core-rdf/blob/dev/apis_core/apis_relations/models.py#L223

This logic does not check for changes in entities themselves as outlined in the example above. 

This means we need to implement a check on entity class change. **I suggest to look into hooking property management into django migrations somehow because:**
* Everytime something about entities changes this change would be transfered to properties
* It's consistent as migrations deal with changes in ontology, and changes in properties are changes in the ontology on a conceptual level

This relates closely to https://github.com/acdh-oeaw/apis-core-rdf/issues/5 and progress should be documented there as this is the last major open issue in the rdf-refactoring effort.

**Comment by steffres** [comment]
main issue which should solve this bug is here: https://github.com/acdh-oeaw/apis-core-rdf/issues/59

**Comment by steffres** [comment]
Come to think of it, this bug should be easily solved by running a check on all properties' `subj_class` and `obj_class` attributes on each Django `migrate` command. As the migrate command would change something about the ontology, hooking the check into this would be very reasonable.
