### ISSUE TITLE
RDF parser needs to have a setting to set the base URL for a definition

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/apis-core-rdf#600]
currently we just iter through all existing definitions and if the SPARQL returns results take the definition:

https://github.com/acdh-oeaw/apis-core-rdf/blob/8b6fe1ec545c7230a238bab9d66de1401db8c401/apis_core/utils/rdf.py#L29-L33

However, ontologies reuse other ontologies a lot, eg `rdfs` or `schema.org`. We can not be sure that every ontology always reuses other ontologies the same way. Therefore we want to have a check on the base-domain of the URI and decide based on that which definitions to use for which URIs.

**Comment by b1rger** [comment]
IIRC that was deliberate decision to drop the `base_url` from the yaml and replace it with the `filter_sparql`. I'm not happy with the current solution either, because everything is in one big file.

You can pass a `settings_file` to the `get_modelname_and_dict_from_uri` method, though.

We would have to think about the use cases - if the `Importer` is the only place where RDF parsing is done, than I would probably propose to implement an abstract `RDFImporter` class that contains the logic and then ship separate child classes `PlaceFromGeonamesImporter`, `PlaceFromDNBImporter`, etc that inherit from `RDFImporter` and point to the correct defintion. (This would just move the responsibility of choosing the right importer to the user configuring the model importer, though - I'm not sure it we have a 1:1 match from domain to defintion - we have already two defintions for geonames...)

**Comment by sennierer** [comment]
I agree with the baseclass idea, that was the case with the vanilla RDFParser, just that we had only this class and then config files. Subclassing would be more clean and easier to read/debug.
Apart from that I was wrong, as there is now `ASK` clauses to test whether the config is correct it can be done very precisely now. I will just split the config and import it in every importer class for maintainability (so only the OEBL version for starters).
Closing this.
