### ISSUE TITLE
history: `verbose_name` and `verbose_name_plural` should include the models `verbose_name`

### ISSUE THREAD

**Issue by b1rger** [acdh-oeaw/apis-core-rdf#920]
Currently, all history models are called `Version` (or `Versions` in plural). This is due to 
https://github.com/acdh-oeaw/apis-core-rdf/blob/ced59f45704b146d4a512bdef53c6b3df7c3f0f7/apis_core/history/models.py#L132-L134

we should reuse the models verbose name, so we can differentiate between versions of different models

**Comment by koeaw** [comment]
> we should reuse the models verbose name, so we can differentiate between versions of different models

Agree. I'm also thinking that something like "versioned" (-ed) might make for a better prefix because it's more specific, or descriptive with regard to what it is (for).

"Version" can mean a range of things, e.g. I usually think of "variation" or alternative version when I come across the word, not version as in versioning. For the latter, I already need to be aware of the context or need context clues.
